name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.9.13
  - pip=20.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3,
    - opencv-python==4.6.0.66
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.7.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.21.1
    - torchmetrics==0.7.0
    - kornia==0.6
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
