name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10.4
  - pip=22.2.2
  - libgfortran==5.0.0.dev0
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.2
  - pip:
    - albumentations==1.2.1
    - opencv-python==4.6.0.66
    - pudb==2022.1.2
    - imageio==2.21.1
    - imageio-ffmpeg==0.4.7
    - pytorch-lightning==1.7.2
    - omegaconf==2.2.3
    - test-tube>=0.7.5
    - streamlit>=1.12.0
    - einops==0.4.1
    - torch-fidelity==0.3.0
    - transformers==4.21.1
    - torchmetrics==0.9.3
    - kornia==0.6.6
    - invisible_watermark==0.1.5
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
